# Generated by Django 3.0.4 on 2024-05-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('dat_telecharg', models.DateField()),
                ('dossier', models.FileField(null=True, upload_to='public')),
            ],
        ),
    ]
